In [1]:
import numpy as np

In [2]:
# https://en.wikipedia.org/wiki/Cross-correlation
# https://en.wikipedia.org/wiki/Pearson_correlation_coefficient
# https://mathbitsnotebook.com/Algebra1/FunctionGraphs/FNGContinuousDiscrete.html

x = np.arange(10)
y = 2 * np.sqrt(np.arange(10) + 20)

# https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html
# each row of x, y holds a different variable, with observations in the columns
np.corrcoef(np.arange(10), 2 * np.sqrt(np.arange(10) + 20))
# [[r_xx = 1.0, r_xy], [r_yx, r_yy = 1.0]] where r is person correlation coefficient

array([[1.        , 0.99966095],
       [0.99966095, 1.        ]])

In [3]:
# https://numpy.org/doc/stable/reference/generated/numpy.correlate.html

x = [1, 2, 3]
y = [0, 1, 0.5]

# will return one value - cross-correlation between 2 discrete
# deterministic with time shift 0 (lag)
print(np.correlate(x, y))

# will return len(x) = n values, where
print(np.correlate([1, 2, 3], [0, 1, 0.5], "same"))  # out of len(x)
print(
    np.correlate([1, 2, 3], [0, 1, 0.5], "full")
)  # output of len(x) - len(y) + 1 + 2 * (len(y) - 1) = len(x) + len(y) - 1

[3.5]
[2.  3.5 3. ]
[0.5 2.  3.5 3.  0. ]


In [4]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 4])

# r([1, 2, 3], [2, 3, 4]), r([2, 3, 4], [2, 3, 4]), r([3, 4, 5], [2, 3, 4])
print(np.correlate(x, y))
# r([0, 1, 2], [2, 3, 4]) - lag=-1, np.correlate(x, y), r([4, 5, 0], [2, 3, 4]) - lag=1
print(np.correlate(x, y, "same"))
print(np.correlate(x, y, "full"))

[20 29 38]
[11 20 29 38 23]
[ 4 11 20 29 38 23 10]
